{% set name = "intake-dremio" %}
{% set version = "0.2.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 02232073ca0df72e594a92edb1a5bf969e5f3f0d43feedf3e36f187507def98e

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - intake <2
    - pandas
    - python >={{ python_min }}
    - pyarrow >=14.0
    - libarrow-flight

test:
  imports:
    - intake_dremio
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/intake/intake-dremio
  summary: Intake driver to load data from Dremio
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - philippjfr
